### ISSUE TITLE
What to do for 7.4?

### ISSUE THREAD

**Issue by p1u3o** [flathub/org.freedesktop.Sdk.Extension.php73#11]
7.4 is around the corner, would the best way to proceed be making `org.freedesktop.Sdk.Extension.php74`

@TingPing @nedrichards

**Comment by Lctrs** [comment]
It follows what we are doing with the other SDK extensions (`node`, `openjdk`, etc.). IMHO, it's the obvious way to go.

**Comment by p1u3o** [comment]
I think the other SDK extensions use major versions.

Maybe it's better to have a future extension as `org.freedesktop.Sdk.Extension.php7` which would track the latest PHP 7 release.

**Comment by Lctrs** [comment]
Problem is that PHP doesn't follow SemVer. So code that works with PHP `7.3` could not work with PHP 7.4. I think an extension per minor PHP version is the best.

**Comment by stobbsm** [comment]
I agree with @Lctrs on this one. PHP is known to break between minor releases, since version 4.
Eventually, the idea would be to remove the php73 extension when it is no longer supported, and let people pick one or the other until such a time.

**Comment by p1u3o** [comment]
That sounds like good reasoning.

~~What do you think of an idea of moving away from the `org.freedesktop.Sdk.Extension` namespace and to something like `net.php`. PHP isn't really related to the desktop and we'd no longer have to maintain a branch for each version of the freedesktop runtime. It would have to be tested, but nothing jumps out at why PHP built on 18.08 wouldn't run on 19.08.~~

**Comment by Lctrs** [comment]
PR is here : https://github.com/flathub/flathub/pull/1280

Please answer if you want to be added as maintainers or not.

**Comment by p1u3o** [comment]
That's awesome, I responded over there.

**Comment by Lctrs** [comment]
flathub/flathub#1280 has been merged. This can be closed now.
